Description of realnoiselet
realnoiselet
PURPOSE
Real-valued Noiselet Transform
SYNOPSIS
This is a script file.
DESCRIPTION
    Real-valued Noiselet Transform
    Usage: w = realnoiselet(x)
    x must be a REAL VALUED COLUMN VECTOR or MATRIX
    m = size(x,1) must be a POWER OF TWO
    Notes:
    1) This implementation uses exactly m*log2(m) additions/subtractions.
    2) This is a real-valued variation of "dragon" noiselets.
    3) This is symmetric and orthogonal. To invert, apply again and
       divide by m.
    Written by: Justin Romberg, Georgia Tech
                Peter Stobbe, Caltech
    Email: jrom@ece.gatech.edu, stobbe@acm.caltech.edu
    Created: October 2006
    Last Modified: December 2006
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
readme ----------L1 Homotopy Package-------------+
A_n Takes noiselet measurements.
At_n Takes transpose of noiselet measurements.
SOURCE CODE
%    Real-valued Noiselet Transform
%
%    Usage: w = realnoiselet(x)
%    x must be a REAL VALUED COLUMN VECTOR or MATRIX
%    m = size(x,1) must be a POWER OF TWO
%
%    Notes:
%    1) This implementation uses exactly m*log2(m) additions/subtractions.
%    2) This is a real-valued variation of "dragon" noiselets.
%    3) This is symmetric and orthogonal. To invert, apply again and
%       divide by m.
%
%    Written by: Justin Romberg, Georgia Tech
%                Peter Stobbe, Caltech
%    Email: jrom@ece.gatech.edu, stobbe@acm.caltech.edu
%    Created: October 2006
%    Last Modified: December 2006