Description of soft
soft
PURPOSE
SYNOPSIS
function y = soft(x,T)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
script_simulation_adpWBPDN partial script for running different solvers for adaptive reweighting
script_simulation_wtBPDN partial script for running different solvers
demo_KalmanRWT demo_KalmanRWT
demo_dynamicRWT demo_dynamicRWT
demo_streaming demo_streaming
demo_streamingDWT demo_streamingDWT
demo_streamingLOT demo_streamingLOT
SpaRSA_adpW SpaRSA version 2.0, December 31, 2007
SOURCE CODE
function y = soft(x,T)
if sum(abs(T(:)))==0
   y = x;
else
   y = max(abs(x) - T, 0);
   y = y./(y+T) .* x;
end