Description of fig
fig
PURPOSE
SYNOPSIS
function h = fig(varargin)
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
BPDN_homotopy_demo BPDN_homotopy_demo.m
DS_homotopy_demo DS_homotopy_demo_test.m
demo_wtBPDN demo_wtBPDN
wtBPDN_adaptive_function wtBPDN_adaptive_function
wtBPDN_homotopy_test BPDN_homotopy_Weighted
demo_BPDN demo_BPDN
demo_KalmanRWT demo_KalmanRWT
demo_streaming demo_streaming
demo_streamingDWT demo_streamingDWT
demo_streamingLOT demo_streamingLOT
SOURCE CODE
function h = fig(varargin)
    if mod(numel(varargin),2)
        f = varargin{1};
        parameters = varargin(2:end);
    else
        parameters = varargin;
        f = [];
    end
    if ishandle(f)
        set(0,'CurrentFigure',f);
    elseif ~isempty(f)
        f = figure(f);
    else
        f = figure; shg;
    end
    if ~isempty(parameters)
        set(f,parameters{:});
    end
    if nargout == 1
        h = f;
    end
end