Description of mvprod
mvprod
PURPOSE
function lhs = mvprod(A,rhs,Gamma,flag)
SYNOPSIS
This is a script file.
DESCRIPTION
 function lhs = mvprod(A,rhs,Gamma,flag)
   Usage: lhs = mvprod(A,rhs,Gamma,flag);
   flag = 0: lhs = A_Gamma * rhs
   otherwise: lhs = A_Gamma' * rhs
  Matrix vector multiplication using indices of the matrix.
  Written by: Salman Asif, Georgia Tech
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
l1homotopy l1homotopy.m
l1homotopy_v1 l1homotopy_v1.m
compute_delx This function solves a system of the form A^TA delx = z.
SOURCE CODE
% function lhs = mvprod(A,rhs,Gamma,flag)
%   Usage: lhs = mvprod(A,rhs,Gamma,flag);
%   flag = 0: lhs = A_Gamma * rhs
%   otherwise: lhs = A_Gamma' * rhs
%
%  Matrix vector multiplication using indices of the matrix.
%  Written by: Salman Asif, Georgia Tech