Description of Compile_FWT
Compile_FWT
PURPOSE
SYNOPSIS
function Compile_FWT
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
fwt fwt.m
fwt2 fwt2.m
ifwt ifwt.m
ifwt2 ifwt2.m
This function is called by:
compile % May need to compile the following mex files.
SOURCE CODE
function Compile_FWT
MEX_OK = 0;
% for file = {'fwt','ifwt','fwt2','ifwt2', 'fwt2_CWT', 'afwt2_CWT',  ...
%         'ifwt2_CWT', 'afwt','afwt2'}
%
%     file = char(file);
%     if exist(file)~=3,
%         MEX_OK = 0;
%         break;
%     end
% end
disp('Compiling Wavelet mex files');
if ~MEX_OK
    Friend = computer;
    isPC = 0;
    if strcmp(Friend(1:2),'PC')
        isPC = 1;
    end
    if isPC
        mex -c fwt_level.c
        mex fwt.c fwt_level.obj -output fwt
        mex ifwt.c fwt_level.obj -output ifwt
        mex fwt2.c fwt_level.obj -output fwt2
        mex ifwt2.c fwt_level.obj -output ifwt2
    else
        mex -c fwt_level.c
        mex fwt.c fwt_level.o -output fwt
        mex ifwt.c fwt_level.o -output ifwt
        mex fwt2.c fwt_level.o -output fwt2
        mex ifwt2.c fwt_level.o -output ifwt2
    end
end