Description of ifwt2
ifwt2
PURPOSE
ifwt2.m
SYNOPSIS
This is a script file.
DESCRIPTION
 ifwt2.m
 Inverse fast 2D wavelet transform.
 Usage: x = ifwt2(w, g0, g1, J, sym);
 x - mxn output image (min(m,n) must be divisible by 2^J)
 w - mxn input image of wavelet coeffients
 g0 - lowpass reconstruction filter
 g1 - highpass reconstruction filter
      g0 and g1 should be zero padded appropriately so that they have the
      same length, and this length is even.
 J - number of levels in the filter bank.
     Right now, it must be chose so that n*2^(-J) >= length(g0)
 sym - How the input was extended when the forward transform was taken.
     sym=0: periodization
     sym=1: type-I symmetric extension ( [... x(2) x(1) x(2) x(3) ...])
            The wavelet filters must have type-I even symmetry
            (e.g. daub79)
     sym=2: type-II symmetric extension ( [... x(2) x(1) x(1) x(2) x(3) ...])
            The lowpass filter must have type-II even symmetry,
            The highpass filter must have type-II odd symmetry.
            (e.g. daub1018)
 Written by: Justin Romberg
 Created: April 2007
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
script_simulation_adpWBPDN partial script for running different solvers for adaptive reweighting
Compile_CWT
Compile_FWT
SOURCE CODE
% ifwt2.m
%
% Inverse fast 2D wavelet transform.
%
% Usage: x = ifwt2(w, g0, g1, J, sym);
% x - mxn output image (min(m,n) must be divisible by 2^J)
% w - mxn input image of wavelet coeffients
% g0 - lowpass reconstruction filter
% g1 - highpass reconstruction filter
%      g0 and g1 should be zero padded appropriately so that they have the
%      same length, and this length is even.
% J - number of levels in the filter bank.
%     Right now, it must be chose so that n*2^(-J) >= length(g0)
% sym - How the input was extended when the forward transform was taken.
%     sym=0: periodization
%     sym=1: type-I symmetric extension ([... x(2) x(1) x(2) x(3) ...])
%            The wavelet filters must have type-I even symmetry
%            (e.g. daub79)
%     sym=2: type-II symmetric extension ([... x(2) x(1) x(1) x(2) x(3) ...])
%            The lowpass filter must have type-II even symmetry,
%            The highpass filter must have type-II odd symmetry.
%            (e.g. daub1018)
%
% Written by: Justin Romberg
% Created: April 2007